target "CSGOConfigs" do
    # Navigation
    pod 'RESideMenu'
    
    # Networking
    pod 'AFNetworking', '~> 3.0'
    pod 'SDWebImage', '~>3.8'
    
    # Layout
    pod 'Masonry'
    
    # UI
    pod 'DGActivityIndicatorView'
    pod 'LCAnimatedPageControl'
    pod 'BMYScrollableNavigationBar'
    
    # DI
    pod 'AppleGuice'
end
